# Lesson: Basics of NumPy

## Introduction

NumPy is a powerful library for numerical computing in Python. It provides support for arrays, matrices, and many mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, including how to create arrays, perform basic operations, and use some of its essential functions.

### Prerequisites
- Basic understanding of Python programming
- Python installed on your machine
- NumPy library installed (`pip install numpy`)


## 1. Importing NumPy

Before using NumPy, you need to import it. The convention is to import it as `np`.

```python
import numpy as np
```


In [1]:
import numpy as np

## 2. Creating Arrays

### 2.1. Creating a NumPy Array

You can create a NumPy array from a Python list using the `np.array()` function.

```python
# Creating a 1D array
arr = np.array([1, 2, 3, 4, 5])
print(arr)
```


In [2]:
# Creating a 1D array
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


### 2.2. Creating Arrays with Zeros, Ones, and a Range of Numbers

NumPy provides functions to create arrays with initial values like zeros, ones, and a range of numbers.

```python
# Creating an array of zeros
zeros_arr = np.zeros(5)
print(zeros_arr)

# Creating an array of ones
ones_arr = np.ones(5)
print(ones_arr)

# Creating an array with a range of numbers
range_arr = np.arange(1, 10, 2)
print(range_arr)
```


In [3]:
# Creating an array of zeros
zeros_arr = np.zeros(5)
print(zeros_arr)

# Creating an array of ones
ones_arr = np.ones(5)
print(ones_arr)

# Creating an array with a range of numbers
range_arr = np.arange(1, 10, 2)
print(range_arr)


[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[1 3 5 7 9]


## 3. Array Operations

### 3.1. Basic Arithmetic Operations

You can perform element-wise arithmetic operations on NumPy arrays.

```python
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Addition
print(arr1 + arr2)

# Subtraction
print(arr1 - arr2)

# Multiplication
print(arr1 * arr2)

# Division
print(arr1 / arr2)
```


In [4]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Addition
print(arr1 + arr2)

# Subtraction
print(arr1 - arr2)

# Multiplication
print(arr1 * arr2)

# Division
print(arr1 / arr2)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


### 3.2. Mathematical Functions

NumPy provides many mathematical functions to operate on arrays.

```python
# Square root
print(np.sqrt(arr))

# Exponential
print(np.exp(arr))

# Sine
print(np.sin(arr))

# Logarithm
print(np.log(arr))
```


In [5]:
# Square root
print(np.sqrt(arr))

# Exponential
print(np.exp(arr))

# Sine
print(np.sin(arr))

# Logarithm
print(np.log(arr))


[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


## 4. Reshaping Arrays

You can change the shape of an array using the `reshape()` function.

```python
# Creating a 1D array
arr = np.arange(1, 10)

# Reshaping to a 2D array
reshaped_arr = arr.reshape(3, 3)
print(reshaped_arr)
```


In [6]:
# Creating a 1D array
arr = np.arange(1, 10)

# Reshaping to a 2D array
reshaped_arr = arr.reshape(3, 3)
print(reshaped_arr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


## 5. Indexing and Slicing

You can access elements of a NumPy array using indexing and slicing.

```python
arr = np.array([1, 2, 3, 4, 5])

# Indexing
print(arr[0])  # First element
print(arr[-1])  # Last element

# Slicing
print(arr[1:4])  # Elements from index 1 to 3
print(arr[:3])  # First three elements
print(arr[2:])  # Elements from index 2 to the end
```


In [7]:
arr = np.array([1, 2, 3, 4, 5])

# Indexing
print(arr[0])  # First element
print(arr[-1])  # Last element

# Slicing
print(arr[1:4])  # Elements from index 1 to 3
print(arr[:3])  # First three elements
print(arr[2:])  # Elements from index 2 to the end


1
5
[2 3 4]
[1 2 3]
[3 4 5]


## 6. Aggregation Functions

NumPy provides various aggregation functions to summarize data.

```python
arr = np.array([1, 2, 3, 4, 5])

# Sum
print(np.sum(arr))

# Mean
print(np.mean(arr))

# Standard Deviation
print(np.std(arr))

# Minimum
print(np.min(arr))

# Maximum
print(np.max(arr))
```


In [8]:
arr = np.array([1, 2, 3, 4, 5])

# Sum
print(np.sum(arr))

# Mean
print(np.mean(arr))

# Standard Deviation
print(np.std(arr))

# Minimum
print(np.min(arr))

# Maximum
print(np.max(arr))


15
3.0
1.4142135623730951
1
5


## Conclusion

In this lesson, we covered the basics of NumPy, including how to create arrays, perform basic operations, and use some of its essential functions. NumPy is a powerful library that provides many more functionalities for numerical computing, and this lesson is just the beginning. Explore more functions and features in the NumPy documentation to enhance your skills.

## Exercises

1. Create a 2D array with shape (3, 4) filled with random numbers.
2. Calculate the sum of all elements in a given array.
3. Reshape a 1D array of 12 elements into a 3x4 matrix.
4. Find the maximum value in a 2D array and its index.
5. Create an array with 10 elements and replace all even numbers with -1.

Happy Learning!